version: '3.8'

services:
  db:
    image: postgres:15
    container_name: delongi-db
    environment:
      POSTGRES_DB: coffee_machine
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
    driver: local
